### ISSUE TITLE
Fails to compile with gcc 4.8.2

### ISSUE THREAD

**Issue by certik** [bluescarni/arbpp#1]
Here is the output for 079140e85252ca02295cab28024feb020b6453e1:

```
$ g++ -std=c++11 -I$HASHSTACK/include -I$HASHSTACK/include/flint main.cpp 
In file included from /home/ondrej/repos/hashstack/default/include/arb.h:31:0,
                 from arbpp.hpp:5,
                 from main.cpp:1:
/home/ondrej/repos/hashstack/default/include/arf.h: In function ‘void arf_set(arf_struct*, const arf_struct*)’:
/home/ondrej/repos/hashstack/default/include/arf.h:222:49: error: invalid conversion from ‘void*’ to ‘mp_ptr {aka long unsigned int*}’ [-fpermissive]
                         (xn) * sizeof(mp_limb_t));          \
                                                 ^
/home/ondrej/repos/hashstack/default/include/arf.h:392:13: note: in expansion of macro ‘ARF_GET_MPN_WRITE’
             ARF_GET_MPN_WRITE(yptr, n, y);
             ^
```

**Comment by fredrik-johansson** [comment]
This problem has already been fixed in Arb (update to 2.2.0 or the git master).

**Comment by bluescarni** [comment]
@fredrik-johansson Ah yes, a missing explicit cast from malloc or something similar right? Ran into that some time ago, was about to submit a pull request but glad it's already fixed :)

**Comment by certik** [comment]
Upgrading Arb fixes it, thanks @fredrik-johansson !
